lib/gatekeeper_web/router.ex
defmodule GatekeeperWeb.Router do
  use GatekeeperWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :requires_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug Guardian.Plug.EnsureAuthenticated, on_failure: { GatekeeperWeb.PageController, :unauthenticated }
  end

  pipeline :application do
    plug Gatekeeper.DoorLockStatusPlug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", GatekeeperWeb do
    pipe_through :browser

    if Application.get_env(:gatekeeper, Gatekeeper.Features)[:automatic_auth] do
      post "/automatic", AuthenticationController, :automatic
    end
    get "/:provider", AuthenticationController, :request
    get "/:provider/callback", AuthenticationController, :callback
    delete "/", AuthenticationController, :delete
  end

  scope "/", GatekeeperWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  scope "/", GatekeeperWeb do
    pipe_through [:browser, :requires_auth, :application]

    resources "/companies", CompanyController do
      resources "/members", MemberController do
        resources "/rfid_tokens", RfidTokenController
      end
    end

    resources "/rfid_tokens", RfidTokenController

    resources "/doors", DoorController do
      post "/flipflop", DoorController, :flipflop
      get "/flipflop", DoorController, :flipflop
    end
    resources "/door_groups", DoorGroupController
    resources "/door_access_attempts", DoorAccessAttemptController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Gatekeeper do
  #   pipe_through :api
  # end
end

lib/gatekeeper_web/controllers/rfid_token_controller.ex
defmodule GatekeeperWeb.RfidTokenController do
  use GatekeeperWeb, :controller

  alias Gatekeeper.Member
  alias Gatekeeper.RfidToken
  alias Gatekeeper.DoorAccessAttempt

  plug :scrub_params, "rfid_token" when action in [:create, :update]

  def index(conn, %{"company_id" => _company_id, "member_id" => member_id}) do
    member = Repo.get!(Member, member_id) |> Repo.preload([:rfid_tokens, :company])
    rfid_tokens = member.rfid_tokens |> Repo.preload([:door_access_attempts, [member: :company]])
    render(conn, "index.html", rfid_tokens: rfid_tokens, member: member)
  end

  def index(conn, _params) do
    rfid_tokens = Repo.all(RfidToken) |> Repo.preload([:door_access_attempts, [member: :company]])
    render(conn, "index.html", rfid_tokens: rfid_tokens, member: nil)
  end

  def new(conn, %{"company_id" => _company_id, "member_id" => member_id}) do
    member = Repo.get!(Member, member_id) |> Repo.preload(:company) |> Repo.preload(:rfid_tokens)
    changeset = RfidToken.changeset %RfidToken{}
    render(conn, "new.html", changeset: changeset, member: member, members: Member.all_active)
  end

  def create(conn, %{"company_id" => _company_id, "member_id" => member_id, "rfid_token" => rfid_token_params}) do
    member = Repo.get!(Member, member_id) |> Repo.preload(:company) |> Repo.preload(:rfid_tokens)
    changeset = RfidToken.changeset(%RfidToken{member_id: String.to_integer(member_id)}, rfid_token_params)

    case WriteRepo.insert(changeset) do
      {:ok, _rfid_token} ->
        conn
        |> put_flash(:info, "RFID Token created successfully.")
        |> redirect(to: company_member_path(conn, :show, member.company, member))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset, member: member, members: Member.all_active)
    end
  end

  def show(conn, params = %{"id" => id}) do
    rfid_token = Repo.get!(RfidToken, id) |> Repo.preload(member: :company)
    query = from daa in DoorAccessAttempt.ordered_preloaded, where: daa.rfid_token_id == ^rfid_token.id
    page = Repo.paginate(query, params)
    render conn, "show.html", rfid_token: rfid_token, member: rfid_token.member, door_access_attempts_page: page
  end

  def edit(conn, %{"company_id" => _company_id, "member_id" => _member_id, "id" => id}) do
    rfid_token = Repo.get!(RfidToken, id) |> Repo.preload(:member)
    member = Repo.preload(rfid_token.member, :company)

    changeset = RfidToken.changeset(rfid_token)
    render(conn, "edit.html", member: member, members: nil, rfid_token: rfid_token, changeset: changeset)
  end

  def edit(conn, %{"id" => id}) do
    rfid_token = Repo.get!(RfidToken, id) |> Repo.preload(member: :company)
    changeset = RfidToken.changeset(rfid_token)

    render(conn, "edit.html", member: nil, members: Member.all_active, rfid_token: rfid_token, changeset: changeset)
  end

  def update(conn, %{"id" => id, "rfid_token" => rfid_token_params}) do
    rfid_token = Repo.get!(RfidToken, id) |> Repo.preload(:member)
    member = if rfid_token.member do
      Repo.preload(rfid_token.member, :company)
    else
      nil
    end

    # FIXME: Validation, instead of coercion, to ensure the identifier does not change
    rfid_token_params = Map.merge(rfid_token_params, %{"identifier" => rfid_token.identifier})

    changeset = RfidToken.changeset(rfid_token, rfid_token_params)

    case WriteRepo.update(changeset) do
      {:ok, _rfid_token} ->
        destination = if member do
          company_member_path(conn, :show, member.company, member)
        else
          rfid_token_path(conn, :show, rfid_token)
        end

        conn
        |> put_flash(:info, "RFID Token updated successfully.")
        |> redirect(to: destination)
      {:error, changeset} ->
        render(conn, "edit.html", member: member, rfid_token: rfid_token, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    rfid_token = Repo.get!(RfidToken, id) |> Repo.preload(member: :company)
    member = rfid_token.member
    company = member.company

    # Here we use update! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    changeset = RfidToken.changeset(rfid_token, %{active: false})
    WriteRepo.update!(changeset)

    conn
    |> put_flash(:info, "RFID Token deactivated successfully.")
    |> redirect(to: company_member_path(conn, :show, company, member))
  end
end

lib/gatekeeper_web/views/rfid_token_view.ex
defmodule GatekeeperWeb.RfidTokenView do
  use GatekeeperWeb, :view
  alias Gatekeeper.RfidToken
end

lib/gatekeeper_web/templates/rfid_token/edit.html.eex
<h2>Edit RFID token</h2>

<%= render "form.html", Map.merge(@conn.assigns, %{conn: @conn, action: rfid_token_path(@conn, :update, @rfid_token)}) %>

<% # TODO: history(-1) %>
<%= link "Back", to: rfid_token_path(@conn, :show, @rfid_token) %>

lib/gatekeeper_web/templates/rfid_token/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= translate_error(message) %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :identifier, "identifier", class: "control-label" %>
    <!-- Identifiers are locked and unchangeable once created -->
    <%= text_input f, :identifier, class: "form-control", disabled: !!@changeset.data.identifier %>
  </div>

  <%= unless @changeset.data.member_id do %>
    <div class="form-group">
      <label for="member" class="control-label">Assign to Member:</label>
      <select name="rfid_token[member_id]" class="form-control">
        <%= for member <- @members do %>
          <option value="<%= member.id %>"><%= member.name %> (<%= member.company.name %>)</option>
        <% end %>
      </select>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, "Badge name (optional)", class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :active, "Active?", class: "control-label" %>
    <%= checkbox f, :active, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/gatekeeper_web/templates/rfid_token/index.html.eex
<h2>Listing RFID tokens
  <%= if @member do %>
    for <%= link @member.name, to: company_member_path(@conn, :show, @member.company, @member) %>
  <% end %>
</h2>

<%= render "list.html", member: @member, rfid_tokens: @rfid_tokens, conn: @conn %>

<% # TODO: Fix this to a javascript:history(-1) link %>
<%= #link "Back", to: company_path(@conn, :show, @company) %>

lib/gatekeeper_web/templates/rfid_token/list.html.eex
<h4>RFID Tokens
  <%= if @member do %>
    <%= link "Add new RFID token", to: company_member_rfid_token_path(@conn, :new, @member.company, @member), class: "btn btn-default btn-xs" %>
  <% end %>
</h4>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Identifier</th>
      <th>Active?</th>
      <%= unless @member do %>
        <th>Owner</th>
      <% end %>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for rfid_token <- @rfid_tokens do %>
    <tr>
      <td><%= link RfidToken.display_name(rfid_token), to: rfid_token_path(@conn, :show, rfid_token) %></td>
      <td><%= rfid_token.identifier %></td>
      <td><%= rfid_token.active %></td>
      <%= unless @member do %>
        <td>
          <%= if rfid_token.member do %>
            <% member = rfid_token.member %>
            <%= link member.name, to: company_member_path(@conn, :show, member.company, member) %>
            <br>
            <small><%= link member.company.name, to: company_path(@conn, :show, member.company) %></small>
          <% else %>
            Unassigned
          <% end %>
        </td>
      <% end %>

      <td class="text-right">
        <%= if rfid_token.member do %>
          <%= link "Edit", to: rfid_token_path(@conn, :edit, rfid_token), class: "btn btn-default btn-xs" %>
          <%= link "Deactivate", to: rfid_token_path(@conn, :delete, rfid_token), method: :delete, data: [confirm: "This will deactivate this RFID token and prevent it from being used on any door. Are you sure?"], class: "btn btn-danger btn-xs" %>
        <% else %>
          <%= link "Assign Token", to: rfid_token_path(@conn, :edit, rfid_token), class: "btn btn-default btn-xs" %>
        <% end %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

lib/gatekeeper_web/templates/rfid_token/new.html.eex
<h2>New RFID Token</h2>

<%= render "form.html", Map.merge(@conn.assigns, %{conn: @conn, changeset: @changeset, action: company_member_rfid_token_path(@conn, :create, @member.company, @member)}) %>

<%= link "Back", to: company_member_path(@conn, :show, @member.company, @member) %>

lib/gatekeeper_web/templates/rfid_token/show.html.eex
<h2>RFID Token <%= RfidToken.display_name(@rfid_token) %></h2>
<%= if @member do %>
  <h3>Belonging to <%= link @member.name, to: company_member_path(@conn, :show, @member.company, @member) %> with <%= link @member.company.name, to: company_path(@conn, :show, @member.company) %></h3>
<% else %>
  <h3>Unassigned <%= link "Assign Token", to: rfid_token_path(@conn, :edit, @rfid_token), class: "btn btn-default btn-xs" %></h3>
<% end %>

<ul>

  <li>
    <strong>RFID Token Name:</strong>
    <%= @rfid_token.name || "Unset" %>
  </li>

  <li>
    <strong>Identifier:</strong>
    <%= @rfid_token.identifier %>
  </li>

  <li>
    <strong>Active:</strong>
    <%= @rfid_token.active %>
  </li>

</ul>

<%= Phoenix.View.render GatekeeperWeb.DoorAccessAttemptView, "access_log.html", page: @door_access_attempts_page, conn: @conn %>

<%= link "Edit", to: rfid_token_path(@conn, :edit, @rfid_token) %>
|
<%= if @member do %>
  <%= link "Back", to: company_member_path(@conn, :show, @member.company, @member) %>
<% else %>
  <%= link "Back", to: rfid_token_path(@conn, :index) %>
<% end %>
|
<%= link "Deactivate", to: rfid_token_path(@conn, :delete, @rfid_token), method: :delete, data: [confirm: "This will deactivate this RFID token and prevent it from being used on any door. Are you sure?"], class: "btn btn-danger btn-xs" %>