lib/gatekeeper_web/router.ex
defmodule GatekeeperWeb.Router do
  use GatekeeperWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :requires_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug Guardian.Plug.EnsureAuthenticated, on_failure: { GatekeeperWeb.PageController, :unauthenticated }
  end

  pipeline :application do
    plug Gatekeeper.DoorLockStatusPlug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", GatekeeperWeb do
    pipe_through :browser

    if Application.get_env(:gatekeeper, Gatekeeper.Features)[:automatic_auth] do
      post "/automatic", AuthenticationController, :automatic
    end
    get "/:provider", AuthenticationController, :request
    get "/:provider/callback", AuthenticationController, :callback
    delete "/", AuthenticationController, :delete
  end

  scope "/", GatekeeperWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  scope "/", GatekeeperWeb do
    pipe_through [:browser, :requires_auth, :application]

    resources "/companies", CompanyController do
      resources "/members", MemberController do
        resources "/rfid_tokens", RfidTokenController
      end
    end

    resources "/rfid_tokens", RfidTokenController

    resources "/doors", DoorController do
      post "/flipflop", DoorController, :flipflop
      get "/flipflop", DoorController, :flipflop
    end
    resources "/door_groups", DoorGroupController
    resources "/door_access_attempts", DoorAccessAttemptController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Gatekeeper do
  #   pipe_through :api
  # end
end

lib/gatekeeper_web/controllers/door_access_attempt_controller.ex
defmodule GatekeeperWeb.DoorAccessAttemptController do
  use GatekeeperWeb, :controller

  alias Gatekeeper.DoorAccessAttempt

  plug :scrub_params, "door_access_attempt" when action in [:create, :update]

  def index(conn, params) do
    page = DoorAccessAttempt.ordered_preloaded |> Gatekeeper.Repo.paginate(params)
    render conn, "index.html", page: page
  end

  def new(conn, _params) do
    changeset = DoorAccessAttempt.changeset(%DoorAccessAttempt{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"door_access_attempt" => door_access_attempt_params}) do
    changeset = DoorAccessAttempt.changeset(%DoorAccessAttempt{}, door_access_attempt_params)

    case WriteRepo.insert(changeset) do
      {:ok, _door_access_attempt} ->
        conn
        |> put_flash(:info, "Door access attempt created successfully.")
        |> redirect(to: door_access_attempt_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    door_access_attempt = Repo.get!(DoorAccessAttempt, id)
    render(conn, "show.html", door_access_attempt: door_access_attempt)
  end

  def edit(conn, %{"id" => id}) do
    door_access_attempt = Repo.get!(DoorAccessAttempt, id)
    changeset = DoorAccessAttempt.changeset(door_access_attempt)
    render(conn, "edit.html", door_access_attempt: door_access_attempt, changeset: changeset)
  end

  def update(conn, %{"id" => id, "door_access_attempt" => door_access_attempt_params}) do
    door_access_attempt = Repo.get!(DoorAccessAttempt, id)
    changeset = DoorAccessAttempt.changeset(door_access_attempt, door_access_attempt_params)

    case WriteRepo.update(changeset) do
      {:ok, door_access_attempt} ->
        conn
        |> put_flash(:info, "Door access attempt updated successfully.")
        |> redirect(to: door_access_attempt_path(conn, :show, door_access_attempt))
      {:error, changeset} ->
        render(conn, "edit.html", door_access_attempt: door_access_attempt, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    door_access_attempt = Repo.get!(DoorAccessAttempt, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    WriteRepo.delete!(door_access_attempt)

    conn
    |> put_flash(:info, "Door access attempt deleted successfully.")
    |> redirect(to: door_access_attempt_path(conn, :index))
  end
end

lib/gatekeeper_web/views/door_access_attempt_view.ex
defmodule GatekeeperWeb.DoorAccessAttemptView do
  use GatekeeperWeb, :view
  import Scrivener.HTML
end

lib/gatekeeper_web/templates/door_access_attempt/access_log.html.eex
<h4>Access Log</h4>
<%= if length(@page.entries) > 0 do %>
  <table class="table">
    <tr>
      <th>Allowed</td>
      <th>When</th>
      <th>Who</th>
      <th>Where</th>
    </tr>
    <%= for access_attempt <- @page.entries do %>
      <tr class="door_access_attempt_allowed_<%= access_attempt.access_allowed %>">
        <td>
          <%= if access_attempt.access_allowed do %>
            <!-- TODO: Replace with icons -->
            Yes
          <% else %>
            No: <%= access_attempt.reason %>
          <% end %>
        </td>
        <td>
          <%
            time_zone = Timex.Timezone.get("America/New_York")
            local_time = Timex.Timezone.convert(access_attempt.inserted_at, time_zone)
            {:ok, date} = Timex.format(local_time, "%a, %b %e, %Y", :strftime)
            {:ok, time} = Timex.format(local_time, "%l:%M %P", :strftime)
          %>
          <%= date %><br>
          <%= time %>
        </td>
        <td>
          <%= if member = access_attempt.member do %>
            <%= link member.name, to: company_member_path(@conn, :show, member.company, member) %>
            <br>
            <small><%= link member.company.name, to: company_path(@conn, :show, member.company) %></small>
          <% else %>
            <%= link "Unassigned Token: #{access_attempt.rfid_token.identifier}", to: rfid_token_path(@conn, :show, access_attempt.rfid_token) %>
          <% end %>
        </td>
        <td><%= link access_attempt.door.name, to: door_path(@conn, :show, access_attempt.door) %></td>
      </tr>
    <% end %>
  </table>
  <%= pagination_links @page %>
<% else %>
  <p class="no-associations">No attempts to access a door</p>
<% end %>

lib/gatekeeper_web/templates/door_access_attempt/edit.html.eex
<h2>Edit door access attempt</h2>

<%= render "form.html", changeset: @changeset,
                        action: door_access_attempt_path(@conn, :update, @door_access_attempt) %>

<%= link "Back", to: door_access_attempt_path(@conn, :index) %>

lib/gatekeeper_web/templates/door_access_attempt/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= translate_error(message) %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :door_id, "Door", class: "control-label" %>
    <%= number_input f, :door_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :rfid_token_id, "Rfid token", class: "control-label" %>
    <%= number_input f, :rfid_token_id, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :access_allowed, "Access allowed", class: "control-label" %>
    <%= checkbox f, :access_allowed, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/gatekeeper_web/templates/door_access_attempt/index.html.eex
<%= render "access_log.html", page: @page, conn: @conn %>

lib/gatekeeper_web/templates/door_access_attempt/new.html.eex
<h2>New door access attempt</h2>

<%= render "form.html", changeset: @changeset,
                        action: door_access_attempt_path(@conn, :create) %>

<%= link "Back", to: door_access_attempt_path(@conn, :index) %>

lib/gatekeeper_web/templates/door_access_attempt/show.html.eex
<h2>Show door access attempt</h2>

<ul>

  <li>
    <strong>Door:</strong>
    <%= @door_access_attempt.door_id %>
  </li>

  <li>
    <strong>Rfid token:</strong>
    <%= @door_access_attempt.rfid_token_id %>
  </li>

  <li>
    <strong>Access allowed:</strong>
    <%= @door_access_attempt.access_allowed %>
  </li>

</ul>

<%= link "Edit", to: door_access_attempt_path(@conn, :edit, @door_access_attempt) %>
<%= link "Back", to: door_access_attempt_path(@conn, :index) %>