lib/gatekeeper_web/router.ex
defmodule GatekeeperWeb.Router do
  use GatekeeperWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :requires_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug Guardian.Plug.EnsureAuthenticated, on_failure: { GatekeeperWeb.PageController, :unauthenticated }
  end

  pipeline :application do
    plug Gatekeeper.DoorLockStatusPlug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/auth", GatekeeperWeb do
    pipe_through :browser

    if Application.get_env(:gatekeeper, Gatekeeper.Features)[:automatic_auth] do
      post "/automatic", AuthenticationController, :automatic
    end
    get "/:provider", AuthenticationController, :request
    get "/:provider/callback", AuthenticationController, :callback
    delete "/", AuthenticationController, :delete
  end

  scope "/", GatekeeperWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  scope "/", GatekeeperWeb do
    pipe_through [:browser, :requires_auth, :application]

    resources "/companies", CompanyController do
      resources "/members", MemberController do
        resources "/rfid_tokens", RfidTokenController
      end
    end

    resources "/rfid_tokens", RfidTokenController

    resources "/doors", DoorController do
      post "/flipflop", DoorController, :flipflop
      get "/flipflop", DoorController, :flipflop
    end
    resources "/door_groups", DoorGroupController
    resources "/door_access_attempts", DoorAccessAttemptController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Gatekeeper do
  #   pipe_through :api
  # end
end

lib/gatekeeper_web/controllers/door_controller.ex
defmodule GatekeeperWeb.DoorController do
  use GatekeeperWeb, :controller

  alias Gatekeeper.Door
  alias Gatekeeper.DoorAccessAttempt
  alias Gatekeeper.DoorLock

  plug :scrub_params, "door" when action in [:create, :update]

  def index(conn, _params) do
    # doors and door_statuses provided globally via plug
    render(conn, "index.html")
  end

  def new(conn, _params) do
    changeset = Door.changeset(%Door{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"door" => door_params}) do
    changeset = Door.changeset(%Door{}, door_params)

    case WriteRepo.insert(changeset) do
      {:ok, _door} ->
        conn
        |> put_flash(:info, "Door created successfully.")
        |> redirect(to: door_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, params = %{"id" => id}) do
    # I could not find a simpler way to preload all the associations while
    # still providing an order to the access_attempts query
    door = Repo.get!(Door, id) |> Repo.preload(:door_groups)
    daa = from daa in DoorAccessAttempt.ordered_preloaded, where: daa.door_id == ^id
    page = Repo.paginate(daa, params)
    render(conn, "show.html", door: door, door_access_attempts_page: page)
  end

  def edit(conn, %{"id" => id}) do
    door = Repo.get!(Door, id)
    changeset = Door.changeset(door)
    render(conn, "edit.html", door: door, changeset: changeset)
  end

  def update(conn, %{"id" => id, "door" => door_params}) do
    door = Repo.get!(Door, id)
    changeset = Door.changeset(door, door_params)

    case WriteRepo.update(changeset) do
      {:ok, door} ->
        conn
        |> put_flash(:info, "Door updated successfully.")
        |> redirect(to: door_path(conn, :show, door))
      {:error, changeset} ->
        render(conn, "edit.html", door: door, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => _id}) do
    conn
    |> put_flash(:error, "Doors may not be deleted.")
    |> redirect(to: door_path(conn, :index))
  end

  def flipflop(conn, %{"door_id" => door_id}) do
    member = Guardian.Plug.current_resource(conn) |> Repo.preload(:rfid_tokens)
    # FIXME: This RFID token ID is a lie! And it can fail if the admin has no token
    access_attempt_params = %{
      access_allowed: true,
      member_id: member.id,
      rfid_token_id: hd(member.rfid_tokens).id,
      door_id: door_id,
      reason: "admin_web_access"
    }
    access_attempt = DoorAccessAttempt.changeset(%DoorAccessAttempt{}, access_attempt_params)
    case WriteRepo.insert(access_attempt) do
      {:ok, _} ->
        case DoorLock.pidof(door_id) do
          :undefined ->
            # Unable to find a door process
            conn
            |> redirect(to: door_path(conn, :index))
          pid ->
            DoorLock.flipflop(pid)
            conn
            |> redirect(to: door_path(conn, :index))
        end
      {:error, _changeset} ->
        conn
        |> put_flash(:error, "Unable to log door access attempt")
        |> redirect(to: door_path(conn, :index))
    end
  end
end

lib/gatekeeper_web/views/door_view.ex
defmodule GatekeeperWeb.DoorView do
  use GatekeeperWeb, :view
end

lib/gatekeeper_web/templates/door/edit.html.eex
<h2>Edit door</h2>

<%= render "form.html", changeset: @changeset,
                        action: door_path(@conn, :update, @door) %>

<%= link "Back", to: door_path(@conn, :index) %>

lib/gatekeeper_web/templates/door/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= translate_error(message) %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, "Name", class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/gatekeeper_web/templates/door/index.html.eex
<h2>Listing doors</h2>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for door <- @doors do %>
    <tr>
      <td>
        <%= link(to: door_door_path(@conn, :flipflop, door), class: "btn btn-warning btn-xs door_lock_#{door.id}_status") do %>
          <i class="fa fa-question-circle" aria-hidden="true"></i>
        <% end %>
        <%= door.name %>
      </td>

      <td class="text-right">
        <%= link "Show", to: door_path(@conn, :show, door), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: door_path(@conn, :edit, door), class: "btn btn-default btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New door", to: door_path(@conn, :new) %>

lib/gatekeeper_web/templates/door/new.html.eex
<h2>New door</h2>

<%= render "form.html", changeset: @changeset,
                        action: door_path(@conn, :create) %>

<%= link "Back", to: door_path(@conn, :index) %>

lib/gatekeeper_web/templates/door/show.html.eex
<h2><%= @door.name %></h2>
<h4>Door Groups</h4>
<p>This door belongs to the following door groups, and will open for anyone who has access to these groups:</p>
<ul>
  <%= if length(@door.door_groups) > 0 do %>
    <%= for door_group <- @door.door_groups do %>
      <li><%= link door_group.name, to: door_group_path(@conn, :show, door_group) %></li>
    <% end %>
  <% else %>
    <p class="no-associations">Not a member of any door group</p>
  <% end %>
</ul>
<br>


<%= Phoenix.View.render GatekeeperWeb.DoorAccessAttemptView, "access_log.html", page: @door_access_attempts_page, conn: @conn %>
<%= link "Edit", to: door_path(@conn, :edit, @door) %>
<%= link "Back", to: door_path(@conn, :index) %>